### ISSUE TITLE
Possible delay in fetching data from the weather API after updating the CSV file and calculating from there

### ISSUE THREAD

**Issue by baipai** [codeforboston/home-energy-analysis-tool#101]
After the user updated the CSV file and started to calculate.

The calculation itself will/may be very fast? But there maybe some possible delay we don't know yet.

**From Steve:**
I believe the main response delay will be in fetching data from the open-meteo weather API -- we don't know yet how long that will take and whether it will vary from a lot. Therefore we need to assume it could take several seconds, hopefully never more than 10-15 seconds, after the .csv file is read to fetch the data and do the calculations. The UI should show the user that the app is calculating during this possible wait time.

**From me:**
Is it possible that estimating the waiting time could be challenging? It might be difficult to be entirely accurate and it needs to consider if there is any connection issue from the user's side. Instead, I suggest:

1. Setting up a transition screen to inform the user that the system is 'calculating' and they may need to wait. 
2. Additionally, I wonder if we can configure it so that if the waiting time exceeds 5 seconds, the 'waiting screen' will appear. Prior to that, it might be acceptable to skip the 'waiting screen'?

--

**Original conversation screenshot:**

> 
> <img width="313" alt="Screen Shot 2023-10-24 at 7 33 08 PM" src="https://github.com/codeforboston/home-energy-analysis-tool/assets/11348330/b66e1510-e5a5-4794-ade5-7ea27c610993">
> <img width="318" alt="Screen Shot 2023-10-24 at 7 33 21 PM" src="https://github.com/codeforboston/home-energy-analysis-tool/assets/11348330/9091f2c5-40c2-46f1-b532-321b4a44968d">
> <img width="302" alt="Screen Shot 2023-10-24 at 7 33 28 PM" src="https://github.com/codeforboston/home-energy-analysis-tool/assets/11348330/f0289a4f-c766-414a-ac46-82a1e6cd35bf">
> 
>

**Comment by thadk** [comment]
Sometimes the weather API times out:
```
GET /react_devtools_backend_compact.js.map 404 - - 14.387 ms
loading geocodeUtil/weatherUtil
[MSW] Warning: intercepted a request without a matching request handler:

  • GET https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress?address=15+Dale+Ave+Gloucester%2C+MA++01930&format=json&benchmark=2020&vintage=Census2020_Census2020?address=15+Dale+Ave+Gloucester%2C+MA++01930&format=json&benchmark=2020&vintage=Census2020_Census2020

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
geocoded -70.663111973536 42.614259215126
[MSW] Warning: intercepted a request without a matching request handler:

  • GET https://archive-api.open-meteo.com/v1/archive?latitude=42.614259215126&longitude=-70.663111973536&daily=temperature_2m_mean&timezone=America%2FNew_York&start_date=2020-10-02&end_date=2022-11-03&temperature_unit=fahrenheit?latitude=42.614259215126&longitude=-70.663111973536&daily=temperature_2m_mean&timezone=America%2FNew_York&start_date=2020-10-02&end_date=2022-11-03&temperature_unit=fahrenheit

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WeatherUtil.getThatWeathaData (/workspaces/home-energy-analysis-tool/heat-stack/app/utils/WeatherUtil.ts:47:21)
    at Module.getConvertedDatesTIWD [as default] (/workspaces/home-energy-analysis-tool/heat-stack/app/utils/date-temp-util.ts:53:25)
    at action (/workspaces/home-energy-analysis-tool/heat-stack/app/routes/_heat+/single.tsx:192:55)
    at Object.callRouteAction (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
    at /workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:4819:21
    at callLoaderOrAction (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:4881:16)
    at async Promise.all (index 1)
    at callDataStrategyImpl (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:4722:17)
    at callDataStrategy (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:3977:19)
    at submit (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:3739:21)
    at queryImpl (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:3668:22)
    at Object.queryRoute (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/router/router.ts:3613:18)
    at handleDataRequest (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/server-runtime/dist/server.js:201:20)
    at requestHandler (/workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/server-runtime/dist/server.js:118:18)
    at /workspaces/home-energy-analysis-tool/heat-stack/node_modules/@remix-run/express/dist/server.js:41:22
POST /single?_data=routes/_heat+/single 500 - - 10504.192 ms

```

**Comment by thadk** [comment]
@AdamFinkle @ethanstrominger
